"""The dashboard's tab panels must be well-formed <div> trees.

Why this exists: on 2026-09-13 a commit that regrouped the Config tab's
boxes left one extra `</div>` behind. It closed `#tab-config` early, so
the Server address box fell OUTSIDE every tab panel and rendered on top
of whatever tab was actually selected -- the Engines tab showed a server
setting above its results table.

Nothing caught it. The suite had 2,334 tests, `node --check` parsed the
inline JavaScript, and the markup is generated by an f-string that
Python was perfectly happy to format. An unbalanced div is not a syntax
error in any of those senses; it is only wrong as a tree, and nothing
was checking the tree.
"""
from __future__ import annotations

import re
from types import SimpleNamespace

from opendarts.live.server import _render_dashboard_html

_DIV_TOKEN = re.compile(r"<div\b[^>]*>|</div>")
_PANEL_OPEN = re.compile(r'<div id="(tab-[a-z-]+)" class="tab-panel')


def _panels(html: str) -> dict[str, int]:
    return {m.group(1): m.start() for m in _PANEL_OPEN.finditer(html)}


def test_no_markup_escapes_between_tab_panels():
    """A panel must stay open until the next one begins.

    The weaker check -- "does each panel reach depth 0 somewhere?" -- is
    not enough, and this was confirmed by re-inserting the real bug: an
    extra `</div>` simply closes the panel EARLIER and still balances, so
    a naive walk sees nothing wrong. What actually went wrong is that
    content ended up in the gap between one panel closing and the next
    opening, where it belongs to no tab and therefore shows on all of
    them. That gap is the thing to assert on.
    """
    html = _render_dashboard_html(3)
    starts = sorted(_panels(html).items(), key=lambda kv: kv[1])
    assert starts, "no tab panels found -- the selector has drifted"

    for index, (name, start) in enumerate(starts):
        if index + 1 >= len(starts):
            break
        next_name, next_start = starts[index + 1]

        depth = 0
        closed_at = None
        for token in _DIV_TOKEN.finditer(html, start):
            if token.start() >= next_start:
                break
            depth += -1 if token.group(0).startswith("</") else 1
            if depth == 0:
                closed_at = token.end()
                break
        assert closed_at is not None, f"{name} never closes before {next_name}"

        gap = html[closed_at:next_start]
        gap = re.sub(r"<!--.*?-->", "", gap, flags=re.S).strip()
        assert not gap, (
            f"{len(gap)} chars are stranded between {name} closing and "
            f"{next_name} opening -- content there belongs to no tab and "
            f"renders on every one of them:\n{gap[:300]}"
        )


def test_server_address_control_lives_inside_the_config_tab():
    """The specific regression: a Config control escaping into every tab.

    Pinned by id rather than by prose so it keeps working if the section
    is reworded.
    """
    html = _render_dashboard_html(3)
    start = _panels(html)["tab-config"]

    depth = 0
    end = None
    for token in _DIV_TOKEN.finditer(html, start):
        depth += -1 if token.group(0).startswith("</") else 1
        if depth == 0:
            end = token.end()
            break
    assert end is not None

    body = html[start:end]
    for control in ('id="server-port"', 'id="server-host"'):
        assert control in body, f'{control} is outside #tab-config'


def test_tab_title_leads_with_the_machine_name(monkeypatch):
    """With several rigs open, every tab used to read the same thing.

    Patches the module REFERENCE, not platform.node itself: the latter
    is the shared stdlib module, visible to every thread for the
    duration of the test.
    """
    import opendarts.live.server as server
    monkeypatch.setattr(server, "platform", SimpleNamespace(node=lambda: "macrig.local"))
    html = _render_dashboard_html(3)
    assert "<title>macrig - opendarts dashboard</title>" in html


def test_tab_title_escapes_the_machine_name(monkeypatch):
    """A hostname is operator-controlled text going into HTML."""
    import opendarts.live.server as server
    monkeypatch.setattr(server, "platform", SimpleNamespace(node=lambda: "a<b>"))
    html = _render_dashboard_html(3)
    assert "<title>a&lt;b&gt; - opendarts dashboard</title>" in html


# ---------------------------------------------------------------------------
# Maintenance (2026-09-17)


def _config_tab(html: str) -> str:
    """Everything between the Config panel opening and the next panel.

    Sliced panel-to-panel rather than by the div walk used above: a
    `</div>` inside one of this tab's long explanatory comments closes the
    walk early, which is a comment-parsing problem and not a markup one.
    The gap between two panels is the region that actually matters here --
    content in it belongs to no tab, which is the bug that walk was
    written to find in the first place.
    """
    starts = sorted(_panels(html).items(), key=lambda kv: kv[1])
    for index, (name, start) in enumerate(starts):
        if name != "tab-config":
            continue
        end = starts[index + 1][1] if index + 1 < len(starts) else len(html)
        return html[start:end]
    raise AssertionError("#tab-config not found")


def test_maintenance_is_the_last_section_of_the_config_tab():
    """LAST, and that is the design: these are the only two controls on
    the page that take the rig away from whoever is looking at it, so they
    sit below every setting rather than among them, where a mis-aimed
    click lands on a dropdown."""
    body = _config_tab(_render_dashboard_html(3))
    assert '<h2 class="config-section-title">Maintenance</h2>' in body
    titles = re.findall(r'<h2 class="config-section-title">([^<]+)</h2>', body)
    assert titles[-1] == "Maintenance", titles


def test_maintenance_has_both_buttons_and_a_note():
    body = _config_tab(_render_dashboard_html(3))
    assert 'id="btn-restart"' in body
    assert 'id="btn-update-restart"' in body
    assert 'id="restart-note"' in body
    assert ">Restart</button>" in body
    assert ">Update and restart</button>" in body


def test_update_and_restart_starts_hidden_so_a_pinned_rig_never_flashes_it():
    """app.js unhides it only once the config document says always_update
    is false. Shipping it visible would show the button for a moment on every
    rig, including the ones where the plain Restart button already pulls
    -- and a button that appears and then vanishes reads as a bug."""
    body = _config_tab(_render_dashboard_html(3))
    tag = re.search(r'<button id="btn-update-restart"[^>]*>', body)
    assert tag is not None
    assert re.search(r"\bhidden(?=[\s/>])", tag.group(0)), tag.group(0)


def test_maintenance_says_capture_does_not_come_back_on_its_own():
    """Deliberate, and therefore stated where the button is: the page
    reloads into a STOPPED rig. A rig that resumed capture by itself would
    open three cameras in an empty room, and just after a deploy is
    exactly when a human should be in the loop."""
    body = _config_tab(_render_dashboard_html(3))
    section = body[body.index("Maintenance</h2>"):]
    assert "capture does <strong>not</strong> start again on its own" in section
    assert "press Start" in section


def test_the_restart_buttons_are_wired_and_ask_first():
    """The JS half: both ids are bound, both go through one confirm()ing
    path, and the update button is the one that sends the body."""
    from opendarts.live.server import _read_dashboard_file

    js = _read_dashboard_file("app.js")
    assert "document.getElementById('btn-restart').onclick" in js
    assert "document.getElementById('btn-update-restart').onclick" in js
    assert "restartRig(false)" in js and "restartRig(true)" in js
    assert "window.confirm(" in js[js.index("async function restartRig"):]
    assert "JSON.stringify({update: true})" in js


def test_a_plain_restart_sends_no_body_at_all():
    """Byte for byte the request FlightDeck has always sent. An empty {}
    would behave identically today, but it would make the plain path
    depend on body parsing the old path never touched."""
    from opendarts.live.server import _read_dashboard_file

    js = _read_dashboard_file("app.js")
    body = js[js.index("async function restartRig"):js.index("document.getElementById('btn-restart').onclick")]
    assert "fetch('/api/restart', {method: 'POST'})" in body


def test_the_restart_poll_waits_for_a_different_pid():
    """/api/restart schedules its SIGTERM half a second out, so the
    process it is about to kill answers /api/health perfectly in the
    meantime. Polling for "answered at all" reloads the page into a server
    that is mid-shutdown, which looks exactly like the restart failing."""
    from opendarts.live.server import _read_dashboard_file

    js = _read_dashboard_file("app.js")
    fn = js[js.index("async function waitForRigToComeBack"):js.index("async function restartRig")]
    assert "'/api/health'" in fn
    assert "body.pid !== oldPid" in fn
    # An older build on the machine being updated may have no pid at all.
    assert "body.pid === undefined" in fn
    assert "location.reload()" in js


def test_maintenance_hides_update_when_the_launcher_already_pulls():
    """HIDDEN, not disabled: there is nothing to enable, and on such a rig
    the plain Restart button already does the job -- which the note has to
    say, or "Restart" silently updating is the same surprise this feature
    was built to remove."""
    from opendarts.live.server import _read_dashboard_file

    js = _read_dashboard_file("app.js")
    fn = js[js.index("function renderMaintenanceNote"):]
    fn = fn[:fn.index("async function waitForRigToComeBack")]
    assert "updateBtn.hidden = !!always" in fn
    assert "Restart also pulls the latest code" in fn


def test_the_maintenance_note_reads_the_flags_from_the_config_document():
    """ONE source for one fact. Both launcher flags are ordinary keys of
    the config document -- the same document the checkbox beside these
    buttons writes -- so the note is drawn from it rather than from a
    second GET /api/restart. Two readers of one flag is exactly how a
    checkbox and the note under it end up disagreeing on screen.

    GET /api/restart still exists and is still tested (FlightDeck reads
    it); what this pins is that the DASHBOARD does not also ask it.
    """
    from opendarts.live.server import _read_dashboard_file

    js = _read_dashboard_file("app.js")
    fn = js[js.index("function renderMaintenanceNote"):]
    fn = fn[:fn.index("async function waitForRigToComeBack")]
    assert "configValue('always_update'" in fn
    assert "configValue('update_on_next_restart'" in fn
    # Every GET of the flags in this file comes from the document. The
    # only /api/restart requests left are the POSTs that actually restart.
    assert "fetch('/api/restart')" not in js
    # ...and the note is redrawn by the one function that applies a
    # document, so a PATCH and the next poll cannot disagree.
    applier = js[js.index("function applyConfigDocument"):]
    applier = applier[:applier.index("async function refreshConfig")]
    assert "renderMaintenanceNote()" in applier


def test_there_is_exactly_one_maintenance_section_holding_all_three_controls():
    """ONE section, three controls. The setting ("Always update on
    restart", a key of the config document) and the two actions that act
    on it (Restart / Update and restart) were built by different hands and
    briefly had a section each; two sections with the same title, one of
    them deciding whether a button in the other is even shown, is how a
    dashboard ends up disagreeing with itself.

    Counted over the WHOLE page, not just the Config tab: a second
    Maintenance heading anywhere is the thing this is watching for.
    """
    html = _render_dashboard_html(3)
    assert html.count('<h2 class="config-section-title">Maintenance</h2>') == 1
    assert html.count('id="always-update-toggle"') == 1

    body = _config_tab(html)
    section = body[body.index("Maintenance</h2>"):]
    assert 'id="always-update-toggle"' in section
    assert 'id="btn-restart"' in section
    assert 'id="btn-update-restart"' in section


def test_the_always_update_checkbox_writes_through_the_config_document():
    """It is a SETTING, so it goes the way every other setting on this tab
    goes -- PATCH /api/config -- and not through the restart route beside
    it. The buttons keep POSTing /api/restart; the checkbox never does."""
    from opendarts.live.server import _read_dashboard_file

    js = _read_dashboard_file("app.js")
    handler = js[js.index("const alwaysUpdateBox = document.getElementById"):]
    handler = handler[:handler.index("});", handler.index("addEventListener")) + 3]
    assert "patchConfig({always_update: on}" in handler
    assert "/api/restart" not in handler
